version: '3.7'

services:
  kb-dev:
    image: kb:latest
    build: .
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./
        target: /src

# docker-compose up -d
# docker-compose down
